// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetGuardGT.Api.Data;

#nullable disable

namespace NetGuardGT.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260613161103_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("NetGuardGT.Api.Models.Incident", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("AssignedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEscalated")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Severity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SiteLocation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TechnicianId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TechnicianId");

                    b.ToTable("Incidents");
                });

            modelBuilder.Entity("NetGuardGT.Api.Models.IncidentHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("FromStatus")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IncidentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TechnicianId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ToStatus")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IncidentId");

                    b.ToTable("IncidentHistories");
                });

            modelBuilder.Entity("NetGuardGT.Api.Models.Technician", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Specialization")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Technicians");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Name = "Carlos Mendez",
                            Specialization = 0
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            Name = "Ana Lopez",
                            Specialization = 0
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            Name = "Luis Perez",
                            Specialization = 1
                        },
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            Name = "Maria Garcia",
                            Specialization = 1
                        },
                        new
                        {
                            Id = 5,
                            IsActive = true,
                            Name = "Roberto Diaz",
                            Specialization = 2
                        },
                        new
                        {
                            Id = 6,
                            IsActive = true,
                            Name = "Sofia Castro",
                            Specialization = 2
                        },
                        new
                        {
                            Id = 7,
                            IsActive = true,
                            Name = "Diego Morales",
                            Specialization = 3
                        },
                        new
                        {
                            Id = 8,
                            IsActive = true,
                            Name = "Laura Torres",
                            Specialization = 3
                        },
                        new
                        {
                            Id = 9,
                            IsActive = true,
                            Name = "Pedro Jimenez",
                            Specialization = 4
                        },
                        new
                        {
                            Id = 10,
                            IsActive = true,
                            Name = "Elena Ruiz",
                            Specialization = 4
                        },
                        new
                        {
                            Id = 11,
                            IsActive = true,
                            Name = "Marco Salazar",
                            Specialization = 0
                        },
                        new
                        {
                            Id = 12,
                            IsActive = true,
                            Name = "Claudia Reyes",
                            Specialization = 1
                        });
                });

            modelBuilder.Entity("NetGuardGT.Api.Models.Incident", b =>
                {
                    b.HasOne("NetGuardGT.Api.Models.Technician", "Technician")
                        .WithMany("Incidents")
                        .HasForeignKey("TechnicianId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Technician");
                });

            modelBuilder.Entity("NetGuardGT.Api.Models.IncidentHistory", b =>
                {
                    b.HasOne("NetGuardGT.Api.Models.Incident", "Incident")
                        .WithMany("History")
                        .HasForeignKey("IncidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Incident");
                });

            modelBuilder.Entity("NetGuardGT.Api.Models.Incident", b =>
                {
                    b.Navigation("History");
                });

            modelBuilder.Entity("NetGuardGT.Api.Models.Technician", b =>
                {
                    b.Navigation("Incidents");
                });
#pragma warning restore 612, 618
        }
    }
}
